### ISSUE TITLE
No such file or directory @ realpath_rec - /Users (Errno::ENOENT)

### ISSUE THREAD

**Issue by nicholashoule** [technicalpickles/homesick#168]
This worked 4 months ago, so I don't know what changed. This is a fresh install of Fedora 26 and RVM.

**OS:**
```
Fedora release 26 (Twenty Six)
NAME=Fedora
VERSION="26 (Workstation Edition)"
KERNEL=4.12.13-300.fc26.x86_64
```

**Development Tools: (Updated and installed these groups.)**
`sudo dnf groupinstall "C Development Tools and Libraries" "Development Tools"`

**Ruby:**
```
rvm 1.29.3 (latest) 
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
```

**Gems:**
```
*** LOCAL GEMS ***

bigdecimal (1.3.2, default: 1.3.0)
bundler-unload (1.0.2)
did_you_mean (1.1.2, 1.1.0)
executable-hooks (1.3.2)
gem-wrappers (1.3.2)
homesick (1.1.5)
io-console (default: 0.4.6)
json (2.1.0, default: 2.0.4)
minitest (5.10.3, 5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.5)
power_assert (1.1.0, 0.4.1)
psych (2.2.4, default: 2.2.2)
rake (12.1.0, 12.0.0)
rdoc (5.1.0, default: 5. 0.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
test-unit (3.2.6, 3.2.3)
thor (0.20.0)
xmlrpc (0.3.0, 0.2.1)
```

**Error:**
```
/home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/actions/file_actions.rb:45:in `realpath': No such file or directory @ realpath_rec - /Users (Errno::ENOENT)
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/actions/file_actions.rb:45:in `realpath'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/actions/file_actions.rb:45:in `ln_s'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/utils.rb:201:in `block in symlink_each'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/utils.rb:188:in `block (2 levels) in each_file'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/utils.rb:162:in `each'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/utils.rb:162:in `block in each_file'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/actions.rb:186:in `block in inside'
	from /home/user1/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `chdir'
	from /home/user1/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `cd'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/actions.rb:186:in `inside'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/utils.rb:158:in `each_file'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/utils.rb:200:in `symlink_each'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/cli.rb:146:in `block (2 levels) in link'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/cli.rb:145:in `each'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/cli.rb:145:in `block in link'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/actions.rb:186:in `block in inside'
	from /home/user1/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `chdir'
	from /home/user1/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/fileutils.rb:120:in `cd'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/actions.rb:186:in `inside'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/lib/homesick/cli.rb:138:in `link'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /home/user1/.rvm/gems/ruby-2.4.2/gems/homesick-1.1.5/bin/homesick:9:in `<top (required)>'
	from /home/user1/.rvm/gems/ruby-2.4.2/bin/homesick:23:in `load'
	from /home/user1/.rvm/gems/ruby-2.4.2/bin/homesick:23:in `<main>'
	from /home/user1/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/user1/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by nicholashoule** [comment]
I think I've made a mistake and this isn't a real issue. After further investigation, the error was correct and the file/path was missing. We can close this issue.
